@startuml
skinparam classAttributeIconSize 0
class Obligatorio2025Application {
}
class ConfiguracionSeguridad {
}
class ControladorAreas {
  servicioAreas : IServicioAreas
  servicioConsultores : IServicioConsultores
  servicioAreas : IServicioAreas
  servicioConsultores : IServicioConsultores
}
class ControladorClientes {
  servicioClientes : IServicioClientes
}
class ControladorConsultores {
  servicioConsultores : ServicioConsultores
  servicioConsultores : ServicioConsultores
}
class ControladorHome {
  servicioUsuarios : IServicioUsuarios
  servicioClientes : IServicioClientes
  servicioPostulantes : IServicioPostulantes
  servicioConsultores : IServicioConsultores
  passwordEncoder : PasswordEncoder
  servicioUsuarios : IServicioUsuarios
  servicioClientes : IServicioClientes
  servicioPostulantes : IServicioPostulantes
  .. (más campos) ..
}
class ControladorIndex {
}
class ControladorMiCuentaCliente {
  servicioClientes : IServicioClientes
  codificador : PasswordEncoder
  servicioClientes : IServicioClientes
}
class ControladorMiCuentaConsultor {
  servicioConsultores : IServicioConsultores
  codificador : PasswordEncoder
  servicioConsultores : IServicioConsultores
}
class ControladorMiCuentaPostulante {
  servicioPostulantes : IServicioPostulantes
  codificador : PasswordEncoder
  servicioPostulantes : IServicioPostulantes
}
class ControladorOfertas {
  servicioClientes : IServicioClientes
  servicioOfertas : IServicioOfertas
  servicioPostulaciones : IServicioPostulaciones
  servicioAreas : IServicioAreas
  servicioClientes : IServicioClientes
  servicioOfertas : IServicioOfertas
  servicioPostulaciones : IServicioPostulaciones
  servicioAreas : IServicioAreas
}
class ControladorPostulaciones {
  servicioPostulaciones : IServicioPostulaciones
  servicioOfertas : IServicioOfertas
  servicioPostulantes : IServicioPostulantes
  servicioPostulaciones : IServicioPostulaciones
  servicioOfertas : IServicioOfertas
  servicioPostulantes : IServicioPostulantes
}
class ControladorPostulantes {
  servicioPostulantes : ServicioPostulantes
  servicioPostulaciones : IServicioPostulaciones
  servicioPostulantes : ServicioPostulantes
  servicioPostulaciones : IServicioPostulaciones
}
class Area {
  id : Integer
  nombre : String
  asignada : Boolean
}
class Cliente {
  rut : Long
  nombre : String
  url : String
}
class Consultor {
}
class Oferta {
}
class OfertaFK {
  id : Integer
  fechaPublicacion : LocalDate
  fechaCierre : LocalDate
  cliente : Cliente
  area : Area
  descripcion : String
  titulo : String
  cantidadVacantes : Integer
  .. (más campos) ..
}
class Postulacion {
}
class PostulacionId {
  idGenerado : Integer
  id : PostulacionId
  fechaPostulacion : LocalDate
  oferta : Oferta
  postulante : Postulante
  usuarioPostulante : String
  idOferta : Integer
}
class Postulante {
  nombreCompleto : NombreCompleto
  cantidadPostulaciones : int
  cedula : Long
  fechanacimiento : LocalDate
  departamento : String
  primerNombre : String
  segundoNombre : String
  primerApellido : String
  .. (más campos) ..
}
class Rol {
  nombreRol : String
}
class Usuario {
}
interface Crear {
}
interface Modificar {
  usuario : String
  clave : String
  roles : Set<Rol>
  activo : boolean
}
class ExcepcionBiosWork {
}
class ExcepcionNoExiste {
}
class ExcepcionTieneVinculos {
}
class ExcepcionYaExiste {
}
interface IRepositorioAreas {
}
interface IRepositorioConsultores {
}
interface IRepositorioOfertas {
}
interface IRepositorioPostulaciones {
}
interface IRepositorioPostulantes {
}
interface IRepositorioUsuarios {
}
interface IRepostorioClientes {
}
interface IServicioAreas {
}
interface IServicioClientes {
}
interface IServicioConsultores {
}
interface IServicioOfertas {
}
interface IServicioPostulaciones {
}
interface IServicioPostulantes {
}
interface IServicioUsuarios {
}
class ServicioAreas {
  repositorioAreas : IRepositorioAreas
  repositorioAreas : IRepositorioAreas
}
class ServicioClientes {
  repositorioClientes : IRepostorioClientes
  repositorioOfertas : IRepositorioOfertas
  codificador : PasswordEncoder
  repositorioClientes : IRepostorioClientes
  repositorioOfertas : IRepositorioOfertas
}
class ServicioConsultores {
  repositorioConsultores : IRepositorioConsultores
  codificador : PasswordEncoder
  repositorioConsultores : IRepositorioConsultores
}
class ServicioDetallesUsuario {
  repositorioUsuarios : IRepositorioUsuarios
  repositorioConsultores : IRepositorioConsultores
  repositorioPostulantes : IRepositorioPostulantes
  repositorioClientes : IRepostorioClientes
  repositorioUsuarios : IRepositorioUsuarios
  repositorioConsultores : IRepositorioConsultores
  repositorioPostulantes : IRepositorioPostulantes
  repositorioClientes : IRepostorioClientes
}
class ServicioOfertas {
  repositorioOfertas : IRepositorioOfertas
  respositorioPostulaciones : IRepositorioPostulaciones
  repositorioOfertas : IRepositorioOfertas
  respositorioPostulaciones : IRepositorioPostulaciones
}
class ServicioPostulaciones {
  repositorioPostulaciones : IRepositorioPostulaciones
  repositorioOfertas : IRepositorioOfertas
  repositorioPostulaciones : IRepositorioPostulaciones
  repositorioOfertas : IRepositorioOfertas
}
class ServicioPostulantes {
  respositorioPostulantes : IRepositorioPostulantes
  repositorioPostulaciones : IRepositorioPostulaciones
  codificador : PasswordEncoder
  respositorioPostulantes : IRepositorioPostulantes
  repositorioPostulaciones : IRepositorioPostulaciones
}
class ServicioUsuarios {
  repositorioUsuario : IRepositorioUsuarios
  repositorioUsuario : IRepositorioUsuarios
}
class UtilidadesArchivos {
}
class Obligatorio2025ApplicationTests {
}
Area --> Boolean
Area --> Integer
Cliente --> Long
Cliente --|> Usuario
Consultor --|> Usuario
ControladorAreas --> IServicioAreas : @Autowired
ControladorAreas --> IServicioAreas
ControladorAreas --> IServicioConsultores : @Autowired
ControladorAreas --> IServicioConsultores
ControladorClientes --> IServicioClientes : @Autowired
ControladorConsultores --> ServicioConsultores : @Autowired
ControladorConsultores --> ServicioConsultores
ControladorHome --> IServicioClientes : @Autowired
ControladorHome --> IServicioClientes
ControladorHome --> IServicioConsultores : @Autowired
ControladorHome --> IServicioConsultores
ControladorHome --> IServicioPostulantes : @Autowired
ControladorHome --> IServicioPostulantes
ControladorHome --> IServicioUsuarios : @Autowired
ControladorHome --> IServicioUsuarios
ControladorHome --> PasswordEncoder : @Autowired
ControladorHome --> PasswordEncoder
ControladorMiCuentaCliente --> IServicioClientes : @Autowired
ControladorMiCuentaCliente --> IServicioClientes
ControladorMiCuentaCliente --> IServicioOfertas : @Autowired
ControladorMiCuentaCliente --> IServicioOfertas
ControladorMiCuentaCliente --> PasswordEncoder : @Autowired
ControladorMiCuentaConsultor --> IServicioConsultores : @Autowired
ControladorMiCuentaConsultor --> IServicioConsultores
ControladorMiCuentaConsultor --> PasswordEncoder : @Autowired
ControladorMiCuentaPostulante --> IServicioPostulantes : @Autowired
ControladorMiCuentaPostulante --> IServicioPostulantes
ControladorMiCuentaPostulante --> PasswordEncoder : @Autowired
ControladorOfertas --> IServicioAreas : @Autowired
ControladorOfertas --> IServicioAreas
ControladorOfertas --> IServicioClientes : @Autowired
ControladorOfertas --> IServicioClientes
ControladorOfertas --> IServicioOfertas : @Autowired
ControladorOfertas --> IServicioOfertas
ControladorOfertas --> IServicioPostulaciones : @Autowired
ControladorOfertas --> IServicioPostulaciones
ControladorPostulaciones --> IServicioOfertas : @Autowired
ControladorPostulaciones --> IServicioOfertas
ControladorPostulaciones --> IServicioPostulaciones : @Autowired
ControladorPostulaciones --> IServicioPostulaciones
ControladorPostulaciones --> IServicioPostulantes : @Autowired
ControladorPostulaciones --> IServicioPostulantes
ControladorPostulantes --> IServicioPostulaciones : @Autowired
ControladorPostulantes --> IServicioPostulaciones
ControladorPostulantes --> ServicioPostulantes : @Autowired
ControladorPostulantes --> ServicioPostulantes
ExcepcionBiosWork --|> Exception
ExcepcionNoExiste --|> ExcepcionBiosWork
ExcepcionTieneVinculos --|> ExcepcionBiosWork
ExcepcionYaExiste --|> ExcepcionBiosWork
Modificar --> Rol
OfertaFK --> Area
OfertaFK --> Cliente
OfertaFK --> Integer
OfertaFK --> LocalDate
OfertaFK --> Postulacion
OfertaFK ..|> Serializable
PostulacionId --> Integer
PostulacionId --> LocalDate
PostulacionId --> Oferta
PostulacionId --> PostulacionId
PostulacionId --> Postulante
PostulacionId ..|> Serializable
Postulante --> LocalDate
Postulante --> Long
Postulante --> MultipartFile
Postulante --> NombreCompleto
Postulante --|> Usuario
ServicioAreas --> IRepositorioAreas : @Autowired
ServicioAreas --> IRepositorioAreas
ServicioAreas ..|> IServicioAreas
ServicioClientes --> IRepositorioOfertas : @Autowired
ServicioClientes --> IRepositorioOfertas
ServicioClientes --> IRepostorioClientes : @Autowired
ServicioClientes --> IRepostorioClientes
ServicioClientes ..|> IServicioClientes
ServicioClientes --> PasswordEncoder : @Autowired
ServicioConsultores --> IRepositorioConsultores : @Autowired
ServicioConsultores --> IRepositorioConsultores
ServicioConsultores ..|> IServicioConsultores
ServicioConsultores --> PasswordEncoder : @Autowired
ServicioDetallesUsuario --> IRepositorioConsultores : @Autowired
ServicioDetallesUsuario --> IRepositorioConsultores
ServicioDetallesUsuario --> IRepositorioPostulantes : @Autowired
ServicioDetallesUsuario --> IRepositorioPostulantes
ServicioDetallesUsuario --> IRepositorioUsuarios : @Autowired
ServicioDetallesUsuario --> IRepositorioUsuarios
ServicioDetallesUsuario --> IRepostorioClientes : @Autowired
ServicioDetallesUsuario --> IRepostorioClientes
ServicioDetallesUsuario ..|> UserDetailsService
ServicioOfertas --> IRepositorioOfertas : @Autowired
ServicioOfertas --> IRepositorioOfertas
ServicioOfertas --> IRepositorioPostulaciones : @Autowired
ServicioOfertas --> IRepositorioPostulaciones
ServicioOfertas ..|> IServicioOfertas
ServicioPostulaciones --> IRepositorioOfertas : @Autowired
ServicioPostulaciones --> IRepositorioOfertas
ServicioPostulaciones --> IRepositorioPostulaciones : @Autowired
ServicioPostulaciones --> IRepositorioPostulaciones
ServicioPostulaciones ..|> IServicioPostulaciones
ServicioPostulantes --> IRepositorioPostulaciones : @Autowired
ServicioPostulantes --> IRepositorioPostulaciones
ServicioPostulantes --> IRepositorioPostulantes : @Autowired
ServicioPostulantes --> IRepositorioPostulantes
ServicioPostulantes ..|> IServicioPostulantes
ServicioPostulantes --> PasswordEncoder : @Autowired
ServicioUsuarios --> IRepositorioUsuarios : @Autowired
ServicioUsuarios --> IRepositorioUsuarios
ServicioUsuarios ..|> IServicioUsuarios
@enduml